### ISSUE TITLE
Serialize "non-compact" python theta sketch

### ISSUE THREAD

**Issue by janagdata** [apache/datasketches-cpp#378]
Hi,

Is there a way to serialise the theta sketch in python such that more values can be added to it when deserialising?

**Comment by AlexanderSaydakov** [comment]
No, only immutable compact Theta sketches can be serialized. This is intentional to discourage bad practices such as serializing and deserializing after each update. I would suggest structuring your process in such a way that the input is processed in batches (or partitions), and each such batch produces a compact sketch. Later those compact sketches can be merged (union operation).
